openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get all users
    post:
      summary: Create a new user
  /users/{id}:
    get:
      summary: Get user by ID
    put:
      summary: Update user by ID
    delete:
      summary: Delete user by ID
  /login:
    post:
      summary: Authenticate user
