openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: A list of users
        '400':
          description: Invalid input
    post:
      summary: Create a new user
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input
  /users/{id}:
    get:
      summary: Get user by ID
      responses:
        '200':
          description: User found
        '404':
          description: User not found
    put:
      summary: Update user by ID
      responses:
        '200':
          description: User updated successfully
        '400':
          description: Invalid input
        '404':
          description: User not found
    delete:
      summary: Delete user by ID
      responses:
        '204':
          description: User deleted successfully
        '404':
          description: User not found
  /login:
    post:
      summary: Authenticate user
      responses:
        '200':
          description: Authentication successful
        '401':
          description: Invalid credentials
